# Generated by Django 3.2.6 on 2021-08-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='url product')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[('1', 'new'), ('2', 'success'), ('3', 'error')], default='1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraping_config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_scraping.scrapingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingConfigDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taging', models.CharField(max_length=200)),
                ('attribute_key', models.CharField(max_length=200)),
                ('attribute_value', models.CharField(max_length=200)),
                ('get_result', models.CharField(blank=True, choices=[('name', 'get data name'), ('price', 'get data price'), ('image_url', 'get data image')], default=None, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scraping_config', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_scraping.scrapingconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('scraping_result', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_scraping.scrapingresult')),
            ],
        ),
    ]
